Repository freeCodeCamp/web3-curriculum, pull requests merged in 2022-07, with the labels that each got.

#18 feat: improve client ui
  .freeCodeCamp/client/components/project-tests.tsx
  .freeCodeCamp/client/components/test.tsx
  .freeCodeCamp/client/styles.css
  .freeCodeCamp/client/templates/landing.tsx
  .freeCodeCamp/tooling/test.js
Labels: status: awaiting review, type: feature

#31 fix: state and client nonsense
  .freeCodeCamp/client/assets/fcc_primary_small.svg
  .freeCodeCamp/client/components/alert.tsx
  .freeCodeCamp/client/components/badge.tsx
  .freeCodeCamp/client/components/block.tsx
  .freeCodeCamp/client/components/console.tsx
  .freeCodeCamp/client/components/controls.tsx
  .freeCodeCamp/client/components/description.tsx
  .freeCodeCamp/client/components/header.tsx
  .freeCodeCamp/client/components/heading.tsx
  .freeCodeCamp/client/components/hints.tsx
  .freeCodeCamp/client/components/integrated-project-controls.tsx
  .freeCodeCamp/client/components/integrated-project-output.tsx
  .freeCodeCamp/client/components/integrated-project-tests.tsx
  .freeCodeCamp/client/components/loader.tsx
  .freeCodeCamp/client/components/output.tsx
  .freeCodeCamp/client/components/project-controls.tsx
  .freeCodeCamp/client/components/project-output.tsx
  .freeCodeCamp/client/components/ruler.tsx
  .freeCodeCamp/client/components/selection.tsx
  .freeCodeCamp/client/components/tag.tsx
  .freeCodeCamp/client/components/test.tsx
  .freeCodeCamp/client/components/tests.tsx
  .freeCodeCamp/client/index.tsx
  .freeCodeCamp/client/templates/integrated-project.tsx
  .freeCodeCamp/client/templates/landing.tsx
  .freeCodeCamp/client/templates/project.css
  .freeCodeCamp/client/templates/project.tsx
  .freeCodeCamp/client/utils/index.ts
  .freeCodeCamp/package-lock.json
  .freeCodeCamp/package.json
  .freeCodeCamp/webpack.config.cjs
Labels: status: blocked

#24 feat: add p2p network project
  .freeCodeCamp/config/projects.json
  .freeCodeCamp/package-lock.json
  .freeCodeCamp/package.json
  .freeCodeCamp/tooling/locales/english/build-a-p2p-network-in-nodejs.md
  .freeCodeCamp/tooling/locales/english/build-a-peer-to-peer-network.md
  .freeCodeCamp/tooling/test-utils.js
  .gitignore
  .vscode/settings.json
  build-a-p2p-network-in-nodejs/README.md
  build-a-peer-to-peer-network/_web3/index.js
  build-a-peer-to-peer-network/clone-node.js
  build-a-peer-to-peer-network/delete-nodes.js
  build-a-peer-to-peer-network/node-1/.env
  build-a-peer-to-peer-network/node-1/add-transaction.js
  build-a-peer-to-peer-network/node-1/blockchain-helpers.js
  build-a-peer-to-peer-network/node-1/index.js
  build-a-peer-to-peer-network/node-1/known-peers.json
  build-a-peer-to-peer-network/node-1/network-helpers.js
  build-a-peer-to-peer-network/node-1/transactions.json
  package-lock.json
  package.json
Labels: status: awaiting review
